# Filename: .github/workflows/publish.yml
# FINAL RECOMMENDED VERSION

name: Build and Publish to JFrog Artifactory

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17 and Maven settings.xml
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: snapshots
          # These lines correctly read from GitHub SECRETS
          server-username: ${{ var.JFROG_USER }}
          server-password: ${{ var.JFROG_TOKEN }}
          # This is the temporary debugging step. Its output is crucial.
          
      - name: DEBUG - Inspect Maven Settings (Temporary)
        run: |
          echo "--- Verifying location and content of settings.xml ---"
          ls -la ~/.m2/
          echo "--- Displaying settings.xml (secrets should be masked by GitHub) ---"
          cat ~/.m2/settings.xml

      - name: Build and Deploy with Maven
        run: mvn -B deploy
        env:
          JFROG_URL: ${{ var.JFROG_URL }} # Keep JFROG_URL as a secret too